### ISSUE TITLE
Améliorer le chargement des images

### ISSUE THREAD

**Issue by maeligg** [maeligg/coronavirus-or-movie#4]
Les images chargent après le reste du contenu. Quelques pistes d'amélioration :
* Compresser / optimiser la taille des images
* Fixer la taille du conteneur pour éviter un reflow de la page
* Preloader l'image suivante à chaque question

**Comment by Mamboleoo** [comment]
Fixed here
https://github.com/maeligg/coronavirus-or-movie/commit/6ea7b651d712d7b5882bf6df72059def0715fca3
